BEGIN;

ALTER TABLE runtime.lifecycle_faults
    DROP CONSTRAINT IF EXISTS lifecycle_faults_fault_code_check;
ALTER TABLE runtime.lifecycle_faults
    ADD CONSTRAINT lifecycle_faults_fault_code_check
    CHECK (fault_code IN (
        'PLAN_PAIR_INCOMPLETE',
        'ENTRY_PLAN_NOT_CONSUMED',
        'ENTRY_REQUEST_NOT_DISPATCHED',
        'ENTRY_EXECUTION_AMBIGUOUS',
        'POSITION_LINEAGE_INCOMPLETE',
        'POSITION_WITHOUT_EXIT_PLAN',
        'POSITION_WITHOUT_EXIT_OWNER',
        'POSITION_WITHOUT_CONFIRMED_INITIAL_PROTECTION',
        'EXIT_REQUEST_NOT_DISPATCHED',
        'EXIT_EXECUTION_AMBIGUOUS',
        'EXCHANGE_POSITION_OWNERSHIP_INVARIANT_BROKEN',
        'EXCHANGE_POSITION_MODE_MISMATCH',
        'EXCHANGE_STATE_DIVERGED',
        'CAPITAL_RESERVATION_STUCK',
        'UNIVERSAL_ENTRY_OBSERVER_RUNTIME_ERROR'
    ));

COMMIT;
