from __future__ import annotations

DISCOVERY_SYMBOLS = (
    "UNIUSDT",
    "LINKUSDT",
    "BTCUSDT",
    "ETHUSDT",
    "XRPUSDT",
    "1000PEPEUSDT",
    "SOLUSDT",
    "DOGEUSDT",
    "ADAUSDT",
)
CONFIRMATION_SYMBOLS = ("AAVEUSDT", "AVAXUSDT", "BNBUSDT", "LTCUSDT", "SUIUSDT")
MARKET_UNIVERSE = DISCOVERY_SYMBOLS + CONFIRMATION_SYMBOLS
PERIOD_TAG = "20260518_20260816"
EXPECTED_DISCOVERY_EVENTS = 1063

