from typing import Protocol

from bybit_workbench.domain.models import InstrumentRules, Order, OrderRequest, Position


class ExchangeAdapter(Protocol):
    @property
    def connected(self) -> bool: ...

    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def instrument_rules(self, symbol: str) -> InstrumentRules: ...

    async def place_order(self, request: OrderRequest) -> Order: ...

    async def cancel_order(self, client_order_id: str) -> Order: ...

    async def positions(self) -> list[Position]: ...
